openapi: 3.0.0
info:
  title: API de Usuários
  description: API simples para gerenciamento de usuários, onde é possível consultar e adicionar usuários.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local
paths:
  /users:
    get:
      summary: Retorna a lista de usuários cadastrados.
      operationId: getUsers
      responses:
        '200':
          description: Lista de usuários.
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: Tesla da Silva
                        email:
                          type: string
                          format: email
                          example: tesla@gmail.com
                        password:
                          type: string
                          example: Model S
    post:
      summary: Adiciona um novo usuário.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nome do usuário.
                  example: Tesla da Silva
                email:
                  type: string
                  format: email
                  description: E-mail do usuário.
                  example: tesla@gmail.com
                password:
                  type: string
                  description: Senha do usuário.
                  example: Model S
              required:
                - name
                - email
                - password
      responses:
        '200':
          description: Usuário adicionado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Usuário adicionado com sucesso.
        '400':
          description: Dados inválidos fornecidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Dados inválidos
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: must be string
                        keyword:
                          type: string
                          example: type
                        path:
                          type: string
                          example: /name
